spring.application.name=EmployeCrud
#database configurattion
spring.datasource.url=jdbc:mysql://localhost:3306/employee_crud
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#optional
spring.jpa.show-sql=true
spring.jpa.properties.format_sql=true
server.port=8081